### ISSUE TITLE
broken end of turn sequence behavior

### ISSUE THREAD

**Issue by sebertram847** [lipefl/swade-tools#289]
Only loading SWADE Tools mod. Scenario: 2+ actors in the combat tracker, make all (or the right one) Stunned. End the round. One actor (and only ever one) will get 2 free rolls to unshake before cards are dealt. If both rolls succeed, the 2nd one throws an error since the condition was removed by the first. I cannot figure out why this happens.

Further research is that the stunned condition is not the issue, it's only proving that at the end of the turn, one combatant goes through 2 or 3 other turn sequences before the beginning of the next round. Something in combatcontrol.js or start.js?

![image](https://github.com/lipefl/swade-tools/assets/56006026/a1225f43-be70-49c7-b374-c7a565cba985)

**Comment by lipefl** [comment]
It seems like they changed combat a little, it could get fixed by itself in the next system updates, but i'll see what can be done.

**Comment by sebertram847** [comment]
I looked over start.js and combatcontrol for an obvious hack but I don’t
know enough about the eventing structure of foundry to be useful. The way
the turn counter goes back to zero at the end of a round broke my brain.

It’s not a game breaker issue but thanks for taking a look at it.

Also this toolkit is great. Thanks for providing it!

**Comment by lipefl** [comment]
I wasn't able to reproduce it anymore. I think it fixed itself in the system update.

**Comment by sebertram847** [comment]
Actually I can still reproduce it. At the end of the round one character gets 2 tries to unshake before the new round starts. Same as above.

**Comment by lipefl** [comment]
You're right, i'll look into it. Thanks

**Comment by lipefl** [comment]
It's fixed now in v1.15.1
Thanks again!

**Comment by sebertram847** [comment]
Yep, works great. Thanks!
